--- #YAML:1.0
name:               Net-MythWeb
version:            0.33
abstract:           Interface to MythWeb
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    DateTime::Format::Strptime:  0
    HTML::TreeBuilder::XPath:  0
    Moose:                0
    MooseX::StrictConstructor:  0
    URI:                  0
    WWW::Mechanize:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
